AWSTemplateFormatVersion: 2010-09-09
Description: Deploy EC2 instances and ALB for Project 1 - Outline of Resources/Parameters

Parameters:

  PrivateSubnet1Id:
    Type: String

  WebInstanceSecurityGroupId:
    Type: String

  PrivateSubnet2Id:
    Type: String

  VPCId:
    Type: String

  ALBSecurityGroupId:
    Type: String

  PublicSubnet1Id:
    Type: String

  PublicSubnet2Id:
    Type: String

Resources:

  WebServerInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ba3677288224cb8c
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroupIds:
        - !Ref WebInstanceSecurityGroupId
      Tags:
        - Key: Name
          Value: production-web-instance-1

  WebServerInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ba3677288224cb8c
      InstanceType: t2.micro
      SubnetId: !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref WebInstanceSecurityGroupId
      Tags:
        - Key: Name
          Value: production-web-instance-2

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      Tags: 
        - Key: Name
          Value: production-alb-tg-web
      Targets: 
        - Id: !Ref WebServerInstance1
          Port: 80
        - Id: !Ref WebServerInstance2
          Port: 80
      TargetType: instance
      VpcId: !Ref VPCId

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Subnets: 
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      Tags: 
        - Key: Name
          Value: production-alb

Outputs:

  ApplicationLoadBalancer:
    Description: The DNS/URL of the ApplicationLoadBalancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: WebsiteURL
